### ISSUE TITLE
Trailing commas not highlighted as errors

### ISSUE THREAD

**Issue by dfellis** [elzr/vim-json#4]
So, my biggest mistakes when writing JSON files are forgetting closing quotes (which this library catches) and forgetting about trailing commas at the end of a list of array values or key-value pairs, which this lib unfortunately doesn't catch.

I've never written a vim syntax highlighting file before, so I'm making this an issue for now, but if I figure out how to add this feature, I'll fork and PR it. :)

**Comment by graingert** [comment]
@elzr actually trailing commas are fine in objects and lists ES2015 and ES2016. In ES2016 it might even be allowed in function parameter and argument lists.

**Comment by dfellis** [comment]
@graingert EMCAScript != JSON

**Comment by graingert** [comment]
> I'm guessing it's always bad form to put a trailing comma but Firefox & Chrome let such a trivial Javascript mistake go

It's not a mistake or bad form

**Comment by dfellis** [comment]
```
damocles@Talyn:~$ node
> var testJSON = '{"foo": 1, "bar": 2, }';
undefined
> JSON.parse(testJSON)
SyntaxError: Unexpected token }
    at Object.parse (native)
    at repl:1:7
    at REPLServer.self.eval (repl.js:110:21)
    at Interface.<anonymous> (repl.js:239:12)
    at Interface.emit (events.js:95:17)
    at Interface._onLine (readline.js:203:10)
    at Interface._line (readline.js:532:8)
    at Interface._ttyWrite (readline.js:761:14)
    at ReadStream.onkeypress (readline.js:100:10)
    at ReadStream.emit (events.js:98:17)
>
```

@graingert it *is* for JSON, which is what this project is for validating.

**Comment by graingert** [comment]
> I'm guessing it's always bad form to put a trailing comma but Firefox & Chrome let such a trivial Javascript mistake go

It's not a mistake or bad form
