### ISSUE TITLE
Errors when loading .json file after recent commit change

### ISSUE THREAD

**Issue by pgilad** [elzr/vim-json#42]
Hi, after recent commit: 7d02a56eba61301e7a667908bf336cc7a0fd1295 I'm getting the following errors when opening a json file:

```
Error detected while processing /Users/pgilad/vimfiles/bundle/vim-json/syntax/json.vim:
line   22:
E121: Undefined variable: g:vim_json_syntax_conceal
E15: Invalid expression: has('conceal') && g:vim_json_syntax_conceal == 1
line   34:
E121: Undefined variable: g:vim_json_syntax_conceal
E15: Invalid expression: has('conceal') && g:vim_json_syntax_conceal == 1
```

This is obviously caused by the fact that those variables have not been loaded yet (as happens in the ftplugin). Should be fixed and somehow guarded against the lack of initialization of those vars.

**Comment by paulcalabro** [comment]
I received the following error on my Centos 6.6 box:

```
"sample.json" 455L, 13246C
Error detected while processing /some_user/.vim/ftplugin/json.vim:
line    1:
E169: Command too recursive
Error detected while processing /usr/share/vim/vim72/ftplugin/json.vim:
line    1:
E169: Command too recursive
Press ENTER or type command to continue
```

It was resolved by commenting out:

```
runtime! ftplugin/json.vim
```

I did the following to setup Vim:

- Added  ```au BufRead,BufNewFile *.json set filetype=json``` to .vimrc
- Created the ```~some_user/.vim/ftplugin/json.vim``` file
