### ISSUE TITLE
Plugin not load because setfiletype is ignored

### ISSUE THREAD

**Issue by gera2ld** [elzr/vim-json#55]
Doesn't work for me. But it works when I added this to my `.vimrc`:
``` vimL
autocmd BufNewFile,BufRead *.json setlocal filetype=json
```
I am using gvim 7.4 on Windows 8.1.
It seems that `ftdetect/json.vim` is using `setfiletype` which is, as the document says, short for:
``` vimL
:if !did_filetype()
:  setlocal filetype={filetype}
:endif
```
And I found a `filetype.vim` in my `$VIMRUNTIME` folder, which will `setf javascript` to a `.json` file. As a result, `setfiletype json` in `ftdetect/json.vim` is ignored.
I am not very familiar with vim files, so I'm wondering if there is any reason to use `setfiletype` instead of `setlocal filetype=`?

BTW, hope this could help with #54 .

**Comment by elzr** [comment]
Hi @gera2ld. Thanks for opening the issue and suggesting a fix.

`setfiletype` was just merged in a day ago in this pull request by @igas https://github.com/elzr/vim-json/pull/53 I just thought it was an equivalent but better command but it seems to be causing trouble for both you and others as you mention (for me it works fine).

Anyway, I just changed `ftdetect/json.vim` to `setlocal filetype=json`. It should be better than `set filetype` alone and while it may not guard us against multiple loadings as `setfiletype`, hopefully it causes no more of this serious not loading trouble.
