### ISSUE TITLE
Add command to convert JSON to YAML (and back again)

### ISSUE THREAD

**Issue by BigBlueHat** [elzr/vim-json#62]
I often find myself with one or the other of these two formats, but it's currently requires copying and pasting the content into (typically) and online conversion thing.

My ideal scenario would be to highlight some JSON (in any type of file...ideally), type a command, and have it update the selection with the YAML (or the other way around).

Insane? Maybe. :stuck_out_tongue_winking_eye:

Awesome? Most definitely! :smile:

**Comment by jkufner** [comment]
Just install [json2yaml](https://www.npmjs.com/package/json2yaml) tool and then enter `:%!json2yaml` or `:%!yaml2json` in Vim.

**Comment by BigBlueHat** [comment]
@jkufner this worked fabulously, btw. :smiley_cat: Thanks!
