### ISSUE TITLE
JSONL support

### ISSUE THREAD

**Issue by exodist** [elzr/vim-json#86]
JSONL is basically a file where each line is a complete JSON structure. This syntax plugin already mostly supports it, however it appears that concealing does not work on the first line (but does on all others?) also auto-detect does not detect it as a json.

**Comment by exodist** [comment]
http://jsonlines.org/

**Comment by anchnk** [comment]
Hi,

That's interesting, I am willing to give it a try. 

Could you provide what are the expected output and what you do actually get with some examples please ?

**Comment by anchnk** [comment]
I gave it a try today with examples from http://jsonlines.org/examples/

I can't reproduce the concealing issue. Only the cursor's line isn't concealed (which appends to be the first one when you open a file). 

However, the auto-detection doesn't work for `jsonl` file extension. I will work on this.
